"""add_keys

Revision ID: fba0c71edb21
Revises: 7e85a0179d43
Create Date: 2026-06-08 23:13:44.997591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba0c71edb21'
down_revision: Union[str, None] = '7e85a0179d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firms', sa.Column('firm_key_hash', sa.String(), nullable=True))
    op.add_column('firms', sa.Column('one_time_admin_key_hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'firms', ['firm_key_hash'])
    op.add_column('user_firm_mappings', sa.Column('status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('icai_membership_number', sa.String(), nullable=True))
    op.drop_constraint('users_firm_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    op.drop_column('users', 'firm_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firm_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_firm_id_fkey', 'users', 'firms', ['firm_id'], ['id'])
    op.drop_column('users', 'icai_membership_number')
    op.drop_column('user_firm_mappings', 'status')
    op.drop_constraint(None, 'firms', type_='unique')
    op.drop_column('firms', 'one_time_admin_key_hash')
    op.drop_column('firms', 'firm_key_hash')
    # ### end Alembic commands ###
